trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureSubscription: 'ado-bcsit'

stages:
- stage: Deploy
  displayName: Deploy to Dev
  jobs:
  - job: DeployACRPE
    displayName: Deploy ACR Private Endpoint
    steps:
    - task: AzureCLI@2
      displayName: 'Deploy ACR Private Endpoint (PowerShell)'
      inputs:
        azureSubscription: '$(azureSubscription)'
        scriptType: pscore
        scriptLocation: inlineScript
        inlineScript: |
          az deployment group create `
            --resource-group "rg-ae-test" `
            --template-file "update-acr-pe.bicep" `
            --parameters registryName="myacrtestsit" vnetName="vnet-ae-test" subnetName="snet-ae-test"
